//so...how do we handle the AI for ghouls?
// what happens is that if there's no wandering or anything to do, it acquires a target...
// so what we need is several "hooks" in the AI script, where we check for methods...
// also, scripts...

// a small chunk of AI logic
// should it be a type or a thing?  if it's a type it's static...




// The Sight behavior allows a creature to see

//some ideas...flood find until...flood search...
//...could "sight" become "sense"
